version: '3.8'

services:
  naughty-api:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  naughty-frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - naughty-api
    restart: always
